
default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  collation: utf8_general_ci
  pool: 5
  database: 'space_wiki'
  username: root
  password: 123456
  host: vh-mysql
  port: 3306

development:
  <<: *default
  database: 'space_wiki'

test:
  <<: *default
  database: 'space_wiki_test'

production:
  <<: *default
  username: root
  password:
  database: 'space_wiki'
  
